services:
  api:
    image: ${IMAGE}
    container_name: mercado-express-api

    restart: unless-stopped

    ports:
      - '${PORT:-3000}:3000'

    env_file:
      - .env

    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'
